CON-2434 resume migration to V2
SkillsFundingAgency/das-employercommitments-v2 pull request #141
Opened 2020-10-13 16:35 UTC by shomavg

2020-10-19 08:40 UTC, hkf-tech requested changes

2020-10-19 09:20 UTC, hkf-tech requested changes

2020-10-19 11:07 UTC, shomavg commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ChangeStatus.cshtml
> +                <div class="govuk-radios">
It is working as mentioned in the AC's.

2020-10-20 08:17 UTC, hkf-tech commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ChangeStatus.cshtml
> +                <div class="govuk-radios">
Pause radio button is not visible in the AC, but please let me know if I am missing something.

2020-10-20 20:00 UTC, hkf-tech commented on src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenRequestingResumeApprenticeshipConfirmationPage.cs
> +            Assert.IsInstanceOf<ViewResult>(result);
var viewResult = (ViewResult)result;
                var viewModel = viewResult.Model;

                Assert.IsInstanceOf<ResumeRequestViewModel>(viewModel);
                var resumeRequestViewModel= (ResumeRequestViewModel) viewModel;

                Assert.AreEqual(_viewModel, resumeRequestViewModel);

2020-10-20 20:03 UTC, hkf-tech approved these changes
Good job.

2020-10-27 11:27 UTC, merged