Con 2417 migrate apprentice details
SkillsFundingAgency/das-employercommitments-v2 pull request #179
Opened 2021-02-18 07:58 UTC by VasanthaKasirajan3008

2021-02-19 09:20 UTC, hkf-tech requested changes

2021-02-19 09:20 UTC, hkf-tech commented on src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapperTests.cs
> +
This file has extra white space on multiple places

2021-02-19 11:35 UTC, VasanthaKasirajan3008 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Extensions/DataLockStatusExtensions.cs
> +    public static class DataLockStatusExtensions
added

2021-02-19 12:35 UTC, VasanthaKasirajan3008 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Extensions/ILinkGeneratorExtensions.cs
> +        public static string ReviewChanges(
done

2021-02-19 12:35 UTC, VasanthaKasirajan3008 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Mappers/Apprentice/ApprenticeshipDetailsRequestToViewModelMapper.cs
> +                    CanEditStatus = !(new List<ApprenticeshipStatus> { ApprenticeshipStatus.Completed, ApprenticeshipStatus.Stopped }).Contains(apprenticeship.Status),
👍

2021-02-19 12:35 UTC, VasanthaKasirajan3008 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Extensions/ILinkGeneratorExtensions.cs
> +            return linkGenerator.CommitmentsLink($"accounts/{accountHashedId}/apprentices/manage/{hashedApprenticeshipId}/details/statuschange");
done

2021-02-23 08:48 UTC, hkf-tech approved these changes

2021-03-04 11:52 UTC, merged