CON-2419 migrate payment priority to commitments v2
SkillsFundingAgency/das-employercommitments-v2 pull request #182
Opened 2021-02-24 17:16 UTC by ChrisJWoodcock

2021-02-26 15:17 UTC, hkf-tech requested changes

2021-02-26 16:09 UTC, ChrisJWoodcock commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/EmployerManageApprenticesController.cs
> +    public class EmployerManageApprenticesController : Controller
Changed to PaymentOrderController - ApprenticeController is getting busy and doesn't really fit with payment order which about providers.

2021-02-26 17:29 UTC, ChrisJWoodcock commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/EmployerManageApprenticesController.cs
> +                        new UpdateProviderPaymentsPriorityRequest
Done

2021-02-26 17:29 UTC, ChrisJWoodcock commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Home/Index.cshtml
> +                    <h2 class="govuk-heading-m"><a id="SetPaymentOrder" href="@Url.CommitmentsV2Link($"/accounts/{Model.AccountHashedId}/apprentices/manage/paymentorder")" class="govuk-link">Set paym
Done

2021-02-26 17:29 UTC, ChrisJWoodcock commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/EmployerManageApprentices/PaymentOrder.cshtml
> +                <input type="submit" class="govuk-button" data-module="govuk-button" value="Save and continue" />
Done

2021-02-26 17:30 UTC, ChrisJWoodcock commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/EmployerManageApprentices/PaymentOrder.cshtml
> +                                <select asp-for="ProviderPaymentOrder[priority-1]" asp-items="Model.ProviderSelectListItems()" aria-label="Select a provider" class="govuk-select das-select--select2">
Done

2021-03-01 09:38 UTC, hkf-tech approved these changes

2021-03-08 15:00 UTC, merged