SV-939 select standard option page
SkillsFundingAgency/das-employercommitments-v2 pull request #245
Opened 2021-08-10 12:34 UTC by ben1stone

2021-08-11 06:05 UTC, dashton82 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/DraftApprenticeship/SelectOption.cshtml
> +                @Html.AntiForgeryToken()
The Antiforgery is automatically added by the filter and isn't required here

2021-08-11 06:05 UTC, dashton82 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/DraftApprenticeship/SelectOption.cshtml
> +                @Html.HiddenFor(x => x.CohortReference)
instead of `@Html.HiddenFor` can we use `<input type="hidden" asp-for="CohortReference"/>`

2021-08-19 12:27 UTC, CodeWolf86 requested changes

2021-08-19 12:27 UTC, CodeWolf86 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/CohortController.cs
> +            if (cohortApprenticeships.DraftApprenticeships.Count() == 1)
Can probably change this to `SingleOrDefault` which gets you 1 if there is only 1 , or null if not, would then simplify your code below.

```
if(draftApprenticeship?.CourseCode != null)
{
  // encode and redirect
}
```

2021-08-19 12:27 UTC, CodeWolf86 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/DraftApprenticeship/SelectOption.cshtml
> +        <input type="hidden" asp-for="DraftApprenticeshipId" />
Do we need to re-post everything from the previous page? if the draft apprenticeship gets saved in the previous add, can we just pull through the id here to retrieve it on the server side post?

2021-08-20 09:52 UTC, CodeWolf86 approved these changes

2021-08-20 09:54 UTC, merged