MAP-112_Enable employer to respond to OLTD request on COMPLETED record
SkillsFundingAgency/das-employercommitments-v2 pull request #356
Opened 2022-10-05 15:01 UTC by ratheeshri1984

2022-10-10 11:05 UTC, cofaulco requested changes

2022-10-10 12:20 UTC, ratheeshri1984 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs
> +
Done

2022-10-10 12:24 UTC, ratheeshri1984 commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs
> +            {
Done

2022-10-10 12:27 UTC, ratheeshri1984 commented on src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenRequestingConfirmApprenticeshipHasValidEndDatePage.cs
> +using System.Threading.Tasks;
Done

2022-10-10 12:29 UTC, ratheeshri1984 commented on src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenPostingConfirmHasValidEndDateChanges.cs
> +using System.Threading.Tasks;
Done

2022-10-10 16:38 UTC, ratheeshri1984 commented on src/SFA.DAS.EmployerCommitmentsV2.Web.UnitTests/Controllers/ApprenticeControllerTests/WhenRequestingConfirmApprenticeshipHasValidEndDatePage.cs
> +                .Setup(m => m.Map<ConfirmHasValidEndDateViewModel>(It.IsAny<ConfirmHasValidEndDateRequest>()))
Done

2022-10-12 08:09 UTC, cofaulco approved these changes

2022-10-26 13:50 UTC, merged