Map 184 accidental stop
SkillsFundingAgency/das-employercommitments-v2 pull request #388
Opened 2022-12-12 14:46 UTC by PoojaGaurav12

2022-12-16 16:02 UTC, cofaulco commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs
> +        public async Task<IActionResult> ApprenticeshipNotEnded(ApprenticeshipNotEndedRequest request)
no unit test for this controller action?

2022-12-16 16:03 UTC, cofaulco commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Controllers/ApprenticeController.cs
> +                    return RedirectToAction(nameof(ApprenticeshipNotEnded), new { viewModel.AccountHashedId, viewModel.ApprenticeshipHashedId });
is there a unit test for this?

2023-01-04 13:56 UTC, jamesmking requested changes

2023-01-04 13:56 UTC, jamesmking commented on src/SFA.DAS.EmployerCommitmentsV2.Web/Views/Apprentice/ApprenticeshipNotEnded.cshtml
> +        </p>
Can we simplify this markup, and remove all the `<br />`. Just use `<p>` tags, it keeps spacing consistent. e.g:
`        <p>
            You do not need to stop this apprenticeship; a completion payment still
            needs to be made to your training provider. Once this has been made the
            apprenticeship will complete automatically.
        </p>
        <p>
            For further information, contact your training provider.
        </p>
        <p>
            <a id="details-back-link" class="govuk-link" href="@Url.Action("ApprenticeshipDetails", new ApprenticeshipDetailsRequest { AccountHashedId = Model.AccountHashedId, ApprenticeshipHashedId = Model.ApprenticeshipHashedId })">Go back to apprentice details</a>
        </p>`

2023-01-16 16:18 UTC, merged